apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-server
  template:
    metadata:
      labels:
        app: frontend-server
    spec:
      containers:
      - name: app
        image: tegexplore/pda-2022:backend-
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: dockercred