apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-server
  template:
    metadata:
      labels:
        app: backend-server
    spec:
      containers:
      - name: app
        image: tegexplore/pda-2022:backend-98a9993
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: dockercred
