apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  selector:
    app: app-server
  ports:
    - protocol: TCP
      port: 5000      
      targetPort: 5000
      nodePort: 32000
