apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: frontend-server
  ports:
    - protocol: TCP
      port: 3000      
      targetPort: 3000
      nodePort: 32000